### PR TITLE
Check if app has VIBRATE permission for haptic feedback

### PR DESCRIPTION
**Pull request by Tyderion**
only vibrate if the permission is granted.

### CODE REVIEW

**Comment by Fleker** [comment]
I agree. For some devices that don't vibrate, like a tablet, there's no reason for haptic feedback. Thus, there's no need for it to be used in every application. I was surprised initially when I got that error. I couldn't see a purpose for it in my app, yet I needed this permission regardless.

**Comment by emptyway** [comment]
please make the vibrate optional... thank you~

**Comment by CedricGatay** [comment]
It can be nice to merge and #50 to allow proper handling of vibration.

**Comment by CedricGatay** [comment]
We need to rebase this one and merge it with #50 IMO, what do you think ?

**Comment by Fleker** [comment]
That sounds good

**Comment by fchauveau** [comment]
closing this PR, cherry-picked in #163 
with removal of forced needed persission

**Pull request closed without merging**
