### PR TITLE
prefixing resources with bp to avoid conflicts with appcompat v7 library

### PR DESCRIPTION
**Pull request by dipenpradhan**
renamed conflicting atrributes

### CODE REVIEW

**Comment by littlefyr** [comment]
isn't `bp` it just begging for future conflicts either with other libs or with someone's app?

Why not prefix with `com_doomonafireball_betterpickers_` that seems highly unlikely to cause unintentional problems ever.

**Comment by CedricGatay** [comment]
`bp` prefix is already used for `BetterPickersDialogFragment` I see no problem in keeping it for the `Switch` part of the lib.
Waiting another POV before merging.

**Comment by CedricGatay** [comment]
Please have a look at #121 when considering this one as the other PR seems more complete (modifying the `Switch` backport in sources to use the renamed attributes).

**Comment by fchauveau** [comment]
using `bp` prefix seems the good way to me.
Ok for merging

**Comment by CedricGatay** [comment]
As #121 is merged, and the feature is the same, I close this one unmerged. Anyway, thanks for your work !

**Pull request closed without merging**
