### PR TITLE
Migrates project to Gradle and removes 3rd party library from code

### PR DESCRIPTION
**Pull request by abeatte**
This converts the project over to Gradle so it can easily be imported into Android Studio. It also creates a dependency to org.jraf:android-switch-backport:1.3.1 as opposed to adding the code directly into source. This allows for other libraries that use android-switch-backport to work alongside android-betterpickers. 

Now, to add the project as a submodule in Android studio all you have to do is
`repositories {
    maven {
        url "http://JRAF.org/static/maven/2"
    }
}
dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    compile project(':android-betterpickers:library')
    compile 'org.jraf:android-switch-backport:1.3.1'
}`

or the simple 

`compile ("com.doomonafireball.betterpickers:library:1.5.2") {
    exclude group: 'com.android.support', module: 'support-v4'
    exclude group: 'org.jraf' module: 'android-switch-backport'
}` 

once the changes are pushed up to maven.

### CODE REVIEW

**Comment by abeatte** [comment]
Hey @derekbrameyer, I'd really like to see these changes get merged in before anything gets too stale. What do you think?

**Comment by CedricGatay** [comment]
Hi @abeatte can you have a look at the branch at https://github.com/code-troopers/android-betterpickers/tree/feature/gradle which is the continuation of your pull request to use gradle instead of maven ?

**Comment by abeatte** [comment]
@CedricGatay, that is one hellofa diff. Looks pretty good. I left a few comments on the branch. Nothing really. Does your branch run and work without issue? If its releasable you should submit a PR to either my branch or @derekbrameyer's and we can keep the pressure to update the library.

**Comment by CedricGatay** [comment]
@abeatte it works without any issue so far, didn't tried to release to sonatype yet.
In fact I am one of the people taking care of this project now (derek has not enough time to continue working on it).
I was planning on merging this branch after the release of the 1.5.3 (which fixes appcompat-v21 compatibility issue), and I was asking you to have a look as you are the initiator of the gradle move.

Gradle will be used soon, Maven is too cumbersome now with Android projects.

**Comment by abeatte** [comment]
Hey @CedricGatay, thats awesome! Yeah, its tough when you start accumulating so many side projects. It's time consuming. So far the PR looks good. 

Is there any work that you need me to do to help out at all?

**Comment by CedricGatay** [comment]
For the moment I don't know exactly what's need to be done, but every help is great, so testing / sorting / discussing on issues and PR could be great !

**Pull request merged**
