### PR TITLE
Changed from v4 SupportFragments Native fragments and removed ABS

### PR DESCRIPTION
**Pull request by ImDevinC**
Updated app calls to API11 to utilize native fragments and the native action bar.  v4 Support is still needed for some of the ViewCompat, ViewPager, etc.

### CODE REVIEW

**Comment by coreydowning** [comment]
+1 this should at least be a possibility.

**Comment by gathas** [comment]
+1 I would prefer this approach

**Comment by trolik** [comment]
+1

**Comment by TheClarkster** [comment]
+1 I would also prefer this.

**Comment by alopix** [comment]
Why would you remove support for Android 2.3?
Even thought market share is declining, a lot of companies still need to develop for 2.3 and up (yes, it's horrible but still required).
At least API level 10 should stay supported!

**Comment by asgarddesigns** [comment]
@alopix You are quite right, but some companies are only targeting > 4.0, which means they aren't using supportFragmentManager; Don't want to use the support libs just so we can use a 3rd party library!

I would suggest overloaded methods so you can use either... if that's not possible, 2 separate build artifacts.

**Comment by alopix** [comment]
@asgarddesigns then I would suggest different branches and artifacts.
betterpickers 1.x which includes support lib and a new artifact 2.x + future branch with android 4+ support. I think using overloaded methods would just complicate things (just like support lib alone already complicates things ;))
hopefully in the near future android 2.3 will finally die a silent death ;)

**Comment by asgarddesigns** [comment]
@alopix It depends - what I have seen, it probably would be easy enough to overload, but I have only had a quick look.

separate versions would certainly be easier, but can be painful to maintain!

**Comment by derekbrameyer** [comment]
Hi everyone, I'm going to pick BetterPickers back up over the next couple of weeks and this is definitely on my radar.

My first goal is to address any current bugs and issue a point release, still pointing to support-v4.

Following that, I'll take a look at how to either remove v4, or package two different branches.

I am tempted to go full minSdkVersion 15 following a point release...

**Comment by coreydowning** [comment]
I've discovered other reasons to use support fragments even in a min SDK 14 app such as child fragment support (fragments inside of fragments).

**Comment by fchauveau** [comment]
Closing this PR as android.support.v4 is no more used in project

**Pull request closed without merging**
