### PR TITLE
Add RadialTime dialog fragment with seconds

### PR DESCRIPTION
**Pull request by turrigni**
to fix radial_time_with_second_header_label.xml layout

### CODE REVIEW

**Comment by turrigni** [comment]
@fchauveau 
have see my patch?

**Comment by fchauveau** [comment]
@turrigni 
yes i've start to look at it.

Look's like you've duplicate most of the initial time picker in another class.
I think it should be a better way to only use actual class and add a param to enabled or not seconds selection.

Because it will be hard to maintain both if we have to do some changes

**Comment by CedricGatay** [comment]
@turrigni do you have enough time to work on this to mutualize the code ?

**Comment by turrigni** [comment]
sorry but i haven't time to work to this feature

**Comment by fchauveau** [comment]
Closing due to old PR and not validated by team.

**Pull request closed without merging**
