### PR TITLE
setTime() on HMS builder

### PR DESCRIPTION
**Pull request by mcginty**
This would be really nice to have when allowing people to modify an existing HMS value. Added fitting code to sample app.

### CODE REVIEW

**Comment by AEFeinstein** [comment]
Seconded

**Comment by leicht-io** [comment]
Indeed. I am also missing this feature A LOT.

**Comment by AEFeinstein** [comment]
Thank you!

**Comment by leicht-io** [comment]
Perfect. Thank you very much!

**Pull request merged**
