### PR TITLE
Fix IllegalStateException: Fragment already added

### LINKED ISSUE #285: java.lang.IllegalStateException: Fragment already added: b{41a6cb78 #2 time_dialog}
I get crashes like this from time to time, but it's rare. I can't reproduce it, but I believe it's related to the TimePicker.
Do you happen to have an idea what can be the reason for this and how could I avoid it?

```
java.lang.IllegalStateException: Fragment already added: b{41a6cb78 #2 time_dialog}
    at android.support.v4.app.n.a (FragmentManager.java:1323)
    at android.support.v4.app.e.a (BackStackRecord.java:940)
    at android.support.v4.app.n.a (FragmentManager.java:1722)
    at android.support.v4.app.n$3.run (FragmentManager.java:612)
    at android.support.v4.app.n.h (FragmentManager.java:1617)
    at android.support.v4.app.n$1.run (FragmentManager.java:517)
    at android.os.Handler.handleCallback (Handler.java:615)
    at android.os.Handler.dispatchMessage (Handler.java:92)
    at android.os.Looper.loop (Looper.java:137)
    at android.app.ActivityThread.main (ActivityThread.java:4856)
    at java.lang.reflect.Method.invokeNative (Native Method)
    at java.lang.reflect.Method.invoke (Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1007)
    at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:774)
    at dalvik.system.NativeStart.main (Native Method)
```

I call it like this:

```
TimePickerBuilder tpb = new TimePickerBuilder().setFragmentManager(mFragmentManager);
                        if (tpb != null && mFragmentManager != null && mFragmentManager.findFragmentByTag(MainFragment.TAG) != null) {
                            tpb.setTargetFragment(mFragmentManager.findFragmentByTag(MainFragment.TAG));
                        }
                        tpb.addTimePickerDialogHandler(new TimePickerDialogFragment.TimePickerDialogHandler() {
                            @Override
                            public void onDialogTimeSet(int reference, int hourOfDay, int minute) {

                            }
                        });
                        tpb.show();
```

### PR DESCRIPTION
**Pull request by devnied**
Close #285

### CODE REVIEW

**Comment by fchauveau** [comment]
Hello @devnied 

What are steps to reproduce this bug ?

**Comment by devnied** [comment]
To reproduce this issue, you can modifiy the sample by duplicate the ligne
`npb.show();` on the file SampleNumberBasicUsage.java and click fast on the button to open the dialog.
After that, close the dialog and the app will crash.

File **SampleNumberBasicUsage** 

```
public class SampleNumberBasicUsage extends BaseSampleActivity
        implements NumberPickerDialogFragment.NumberPickerDialogHandlerV2 {

    private TextView mResultTextView;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.text_and_button);

        mResultTextView = (TextView) findViewById(R.id.text);
        Button button = (Button) findViewById(R.id.button);

        mResultTextView.setText(R.string.no_value);
        button.setText(R.string.number_picker_set);
        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                NumberPickerBuilder npb = new NumberPickerBuilder()
                        .setFragmentManager(getSupportFragmentManager())
                        .setStyleResId(R.style.BetterPickersDialogFragment);
                npb.show();
                npb.show();
            }
        });
    }

    @Override
    public void onDialogNumberSet(int reference, BigInteger number, double decimal, boolean isNegative, BigDecimal fullNumber) {
        mResultTextView.setText(getString(R.string.number_picker_result_value, number, decimal, isNegative, fullNumber));
    }
}
```

**Comment by fchauveau** [comment]
Still not able to reproduce with that.
What about Android and Phone versions ?

**Comment by devnied** [comment]
I can reproduce this issue on many Android version (4.1.1, 5.1.0, 6.0.0).
You can try to reproduce it on an emulator, it's more easier.
You need to click fast on the button "Set number", to call at least two times the OnClickListener.
I can only reproduce it manually.

**Comment by JM-Agrimap** [comment]
I see that you have modified the Builders for the components in your merged commit above. 

This is not the source of the problem outlined above in the code sample. Your builder pattern does a great job of mitigating the problem by not exposing the fragment.

The problem occurs when you wish to reuse the dialog fragment instead of recreating it each time.

I've been experiencing the same sort of problem with the CalendarDatePickerDialogFragment and it is due to the underlying DialogFragment implementation which will merrily add the same component to the fragment transaction twice (and then blows up).

There are several approaches to negate this problem which you can use. Either look for the fragment by tag and remove it prior to  showing or to track internally if the dialog has been shown.
(DialogFragment does track if it has been shown internally but does not expose the value called mShownByMe).

I chose to wrap your implementation with the following pattern.
What I would recommend you do is to extend all of your DialogFragments from a base class maybe something like the following instead of DialogFragment.

```
abstract class ShowOnceDialogFragment extends DialogFragment {

    private boolean shown;

    public boolean isShown() {
        return shown;
    }

    @Override
    public void show(FragmentManager manager, String tag) {
        if (!shown) {
            this.shown = true;
            super.show(manager, tag);
        }
    }

    @Override
    public int show(FragmentTransaction transaction, String tag) {
        if (!shown) {
            this.shown = true;
            return super.show(transaction, tag);
        }

        // TODO: test what happens when -1 is returned
        // it may be better to store the backStackId from the first show() and return it
        return -1;
    }

    @Override
    public void dismiss() {
        super.dismiss();
        this.shown = false;
    }

    @Override
    public void dismissAllowingStateLoss() {
        super.dismissAllowingStateLoss();
        this.shown = false;
    }

    @Override
    public void onDismiss(DialogInterface dialog) {
        super.onDismiss(dialog);
        this.shown = false;
    }
}
```

**Pull request merged**
