### PR TITLE
Added HMSPicker negative duration option

### PR DESCRIPTION
**Pull request by paxxux**
Hi,

as requested in #274 I created a pull request. (I am fairly new to git, and do not have time right now to get into it. Hope it works for you.) 

Greetings,
paxxux

### CODE REVIEW

**Comment by fchauveau** [comment]
Thanks @paxxux 
I'll test it this weekend

**Comment by paxxux** [comment]
great

**Comment by fchauveau** [comment]
@paxxux I didnt forget you. I tested it and it works correctly, I'll merge it soon

**Comment by paxxux** [comment]
Thank you very much! Could you test/merge #279 as well please :-)?

Greetings,
paxxux

**Comment by fchauveau** [comment]
Can you update PR to make it point to branch HMSminus : https://github.com/code-troopers/android-betterpickers/tree/HMSmius
So I will be able do add few things before merging.

Thx

**Comment by fchauveau** [comment]
will be merged via #281

**Pull request closed without merging**
