### PR TITLE
Added setTimeInSeconds and setTimeInMilliseconds to HmsPickerBuilder

### PR DESCRIPTION
**Pull request by vanniktech**
It's just a minor simplification so that the user of the library does not have to convert to hour, minute and second for initializing the time.

### CODE REVIEW

**Comment by vanniktech** [comment]
@fchauveau what's up with this PR?

**Comment by fchauveau** [comment]
Hi @vanniktech 
I'll try to review/merge it in the next days

**Comment by vanniktech** [comment]
@fchauveau alright thanks.

**Comment by fchauveau** [comment]
@vanniktech Merged.

I'll perform a release with other stuffs in few days

**Comment by vanniktech** [comment]
@fchauveau thanks, sounds good!

**Comment by fchauveau** [comment]
@vanniktech published : https://repo1.maven.org/maven2/com/code-troopers/betterpickers/library/2.0.3/

**Pull request merged**
