### PR TITLE
add dark theme to calendar date picker.

### PR DESCRIPTION
**Pull request by Tyderion**
Tried to use the same colors as the RadialTimePicker dark theme. 
image

image

The light still looks the same: 
image

image

### CODE REVIEW

**Comment by dgtale** [comment]
+1 cant wait for it

**Comment by ems305** [comment]
+1

**Comment by zhanghai** [comment]
+1 Needing this

**Comment by zhanghai** [comment]
https://github.com/Tyderion/android-betterpickers/commit/d65b7e65b428b0a860d186370e388d8800489d83#diff-0dc8ab9df43f1b12b1e6f8e01c2b6b08R303

The condition should be `mThemeDark && mDayOfWeekView != null` because it can be null when using the layout for some devices. The null-check is also performed in `updateDisplay()`.

**Comment by CedricGatay** [comment]
Great work, sorry it took too long to be merged, I think PR #152 now make this useless (if you've got time to confirm @nkarasch It could be great)

**Comment by nkarasch** [comment]
No, I only applied custom theming to RadialTimePicker. I didn't touch the calendar.

**Comment by CedricGatay** [comment]
My bad, we should rebase this or even better do the same as you Nicholas to allow custom style.

**Comment by nkarasch** [comment]
If @Tyderion doesn't show interest I'll look into it. The way themes are handled in this library is all over the place.

**Comment by Tyderion** [comment]
Thanks for coming back to this.

I think the theming of this widget should be redone (as you said, it's all over the place) but I never had time to look into proper theming of android components so it would take me quite some time to refactor all this. 

All help is appreciated.
If you've got time to look into this @nkarasch please do. I'd love to see how this can be done better.

**Comment by fchauveau** [comment]
Work have been moved to #198 with additional features to allow custom theming

**Pull request closed without merging**
